#!/bin/bash

# MCP-B Task 3 Setup Helper Script
# This script helps set up environment variables for local development and Cloudflare Workers

set -e

echo "================================================"
echo "MCP-B Cloudflare Workers Setup Helper"
echo "================================================"
echo ""

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if we're in the correct directory
if [ ! -f "package.json" ]; then
    echo -e "${RED}Error: package.json not found${NC}"
    echo "Please run this script from the newWebsite directory"
    exit 1
fi

# Function to prompt for input with default value
prompt_with_default() {
    local prompt="$1"
    local default="$2"
    local value

    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " value
        echo "${value:-$default}"
    else
        read -p "$prompt: " value
        echo "$value"
    fi
}

# Function to prompt for sensitive input (hidden)
prompt_secret() {
    local prompt="$1"
    local value

    read -sp "$prompt: " value
    echo ""
    echo "$value"
}

echo -e "${BLUE}This script will help you set up environment variables for:${NC}"
echo "  1. Local Next.js development (.env.local)"
echo "  2. Local Wrangler preview (.dev.vars)"
echo ""
echo -e "${YELLOW}Note: You'll need Browserbase credentials. Get them from:${NC}"
echo "  https://www.browserbase.com/"
echo ""

read -p "Continue? (y/n) " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Setup cancelled."
    exit 0
fi

echo ""
echo -e "${GREEN}Step 1: Collecting Browserbase credentials${NC}"
echo "-------------------------------------------"

BROWSERBASE_API_KEY=$(prompt_secret "Enter your BROWSERBASE_API_KEY")
BROWSERBASE_PROJECT_ID=$(prompt_with_default "Enter your BROWSERBASE_PROJECT_ID" "")
BROWSERBASE_EXTENSION_ID=$(prompt_with_default "Enter your BROWSERBASE_EXTENSION_ID" "")
BB_REGION=$(prompt_with_default "Enter BB_REGION" "us-east-1")

echo ""
echo -e "${GREEN}Step 2: Cloudflare Turnstile (Optional)${NC}"
echo "-------------------------------------------"
echo "Turnstile provides bot protection. Skip if you don't have it yet."
echo ""

read -p "Do you have Cloudflare Turnstile credentials? (y/n) " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    TURNSTILE_SECRET_KEY=$(prompt_secret "Enter your TURNSTILE_SECRET_KEY")
    TURNSTILE_SITE_KEY=$(prompt_with_default "Enter your NEXT_PUBLIC_TURNSTILE_SITE_KEY" "")
else
    TURNSTILE_SECRET_KEY=""
    TURNSTILE_SITE_KEY=""
fi

echo ""
echo -e "${GREEN}Step 3: Website URL${NC}"
echo "-------------------------------------------"
WEBSITE_URL=$(prompt_with_default "Enter NEXT_PUBLIC_WEBSITE_URL" "http://localhost:3000")

echo ""
echo -e "${BLUE}Creating environment files...${NC}"

# Create .env.local
cat > .env.local << EOF
# Generated by setup-env.sh on $(date)
NEXT_PUBLIC_WEBSITE_URL=$WEBSITE_URL

# Browserbase Configuration
BROWSERBASE_API_KEY=$BROWSERBASE_API_KEY
BROWSERBASE_PROJECT_ID=$BROWSERBASE_PROJECT_ID
BROWSERBASE_EXTENSION_ID=$BROWSERBASE_EXTENSION_ID
BB_REGION=$BB_REGION

# Cloudflare Turnstile (Optional)
EOF

if [ -n "$TURNSTILE_SECRET_KEY" ]; then
    cat >> .env.local << EOF
TURNSTILE_SECRET_KEY=$TURNSTILE_SECRET_KEY
NEXT_PUBLIC_TURNSTILE_SITE_KEY=$TURNSTILE_SITE_KEY
EOF
else
    cat >> .env.local << EOF
# TURNSTILE_SECRET_KEY=
# NEXT_PUBLIC_TURNSTILE_SITE_KEY=
EOF
fi

echo -e "${GREEN}✓ Created .env.local${NC}"

# Create .dev.vars
cat > .dev.vars << EOF
# Generated by setup-env.sh on $(date)
# Used by Wrangler for local development

# Browserbase Configuration
BROWSERBASE_API_KEY=$BROWSERBASE_API_KEY
BROWSERBASE_PROJECT_ID=$BROWSERBASE_PROJECT_ID
BROWSERBASE_EXTENSION_ID=$BROWSERBASE_EXTENSION_ID
BB_REGION=$BB_REGION

# Cloudflare Turnstile (Optional)
EOF

if [ -n "$TURNSTILE_SECRET_KEY" ]; then
    cat >> .dev.vars << EOF
TURNSTILE_SECRET_KEY=$TURNSTILE_SECRET_KEY
EOF
else
    cat >> .dev.vars << EOF
# TURNSTILE_SECRET_KEY=
EOF
fi

echo -e "${GREEN}✓ Created .dev.vars${NC}"

echo ""
echo -e "${GREEN}================================================${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${GREEN}================================================${NC}"
echo ""
echo "Environment files created:"
echo "  ✓ .env.local (for npm run dev)"
echo "  ✓ .dev.vars (for npm run cf:preview)"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo ""
echo "1. Test local development:"
echo "   npm run dev"
echo "   Visit: http://localhost:3000/mcp-b-playground"
echo ""
echo "2. Test Wrangler preview:"
echo "   npm run cf:build"
echo "   npm run cf:preview"
echo ""
echo "3. Deploy to Cloudflare Workers:"
echo "   - Add environment variables in Cloudflare Dashboard"
echo "   - See TASK-3-CLOUDFLARE-SETUP.md section 3.2.3"
echo "   - Run: npm run cf:deploy"
echo ""
echo -e "${BLUE}Important:${NC} Don't forget to:"
echo "  - Create R2 buckets (mcp-b-cache, mcp-b-cache-preview)"
echo "  - Add secrets to Cloudflare Workers dashboard"
echo ""
echo "See TASK-3-CLOUDFLARE-SETUP.md for detailed instructions."
echo ""
